In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./slums_data.csv')

In [3]:
df.head()

                                  Location  Men  Kids  Women  Total Category
0                                 Lingipur  100    36     71    207      Low
1                            Mahabhoisasan   87    37    145    269      Low
2                          Bahadalpur (og)  137   113    133    383     High
3                              Bankual(og)   65    44    144    253      Low
4  Industrial & Colony Area (og) (ward 61)  176    62    113    351   Medium

In [6]:
desc =df['Total'].describe()

In [8]:
type(desc)

pandas.core.series.Series

In [12]:
desc

count    109.000000
mean     320.761468
std       54.399397
min      207.000000
25%      284.000000
50%      314.000000
75%      356.000000
max      448.000000
Name: Total, dtype: float64

In [13]:
desc['25%']

284.0

In [18]:
df[df['Category']=='Low']['Location']

0               Lingipur
1          Mahabhoisasan
3            Bankual(og)
5            Injana (og)
7            Kesura (og)
14           Sijuan (og)
17              Barapita
18          Bhagabatipur
20                 Bhola
28           Ghangapatna
31            Haridamada
36          Krushnanagar
38              Malipada
41                Nuagan
42            Paikarapur
45             Sundarpur
52                Suanga
54          Sisupalagada
55             Barimunda
64             Gandarpur
68            Khairapada
71              Padasahi
72          Raghunathpur
76               Bijipur
87               Sijuput
97     Gangeswarpursasan
107           Krushnapur
Name: Location, dtype: object

In [20]:
df[df['Category']=='Medium']

                                    Location  Men  Kids  Women  Total Category
4    Industrial & Colony Area (og) (ward 61)  176    62    113    351   Medium
8                           Koradakanta (og)  143    71     82    296   Medium
10                   Raghunathpur Jalli (og)  144    36    134    314   Medium
11                        Ranasinghapur (og)  202    31     65    298   Medium
12                                Rokat (og)   91    97    125    313   Medium
16                                Anlapatana  175    37    129    341   Medium
19                                  Bhalunka  146    40     99    285   Medium
21                                  Bhuasuni  120    58    132    310   Medium
22                              Bidyadharpur   78    89    117    284   Medium
23                         Chandaka Jogisahi  133    44    126    303   Medium
24                                  Chudanga  129    79    103    311   Medium
25                                     Dalua  153    58    139    350   Medium
26                                Daruthenga  160    93    103    356   Medium
29                                Giringaput  141    42    139    322   Medium
32                                   Haripur   85    74    143    302   Medium
33                           Jagannathprasad  137    79    123    339   Medium
35                                  Kantabad  100    72    147    319   Medium
37                                 Kujimahal  110    71    113    294   Medium
40                                 Mendhasal  157    40    130    327   Medium
43                            Shyamsundarpur   95    65    126    286   Medium
44                              Similipatana  177    55    121    353   Medium
46                              Tulasadeipur  207    43    104    354   Medium
48                                Damodarpur  161    46    110    317   Medium
50                                Shankarpur  135    65    116    316   Medium
51                               Srinibaspur   62    61    188    311   Medium
57                                  Ostapada  169    76    102    347   Medium
59                                Tangibanta  120    96    135    351   Medium
60                                  Balipada  106    72    147    325   Medium
61                                 Basuaghai  119    59    108    286   Medium
62                                     Dadha  116    60    154    330   Medium
65                               Jhinkardiha  133    62    122    317   Medium
66                                 Kalyanpur   89    83    124    296   Medium
69                                   Marchia  170    60    114    344   Medium
73                                  Balipada  113    54    129    296   Medium
74                             Beguniabarahi  124    76    148    348   Medium
75                               Bhagabanpur  121    36    153    310   Medium
78                                   Kasipur  125    72    111    308   Medium
79                                    Mahura  191    56     91    338   Medium
80                                  Nandapur  129    66    111    306   Medium
82                                  Naragoda  149    35    126    310   Medium
83                              Narasinghpur  102    70    115    287   Medium
86                                 Sahajapur  144    92    115    351   Medium
88                                Subudhipur  136    40    126    302   Medium
89                                   Tamando  156    64     88    308   Medium
91                          Basantapur Sasan  148    48    124    320   Medium
93                             Dadhibamanpur  188    46    107    341   Medium
95                                   Dihapur  148    46    123    317   Medium
96                            Durgapurpatana  133    47    131    311   Medium
100                                   Itipur  154    50    139    343   Medium
101                        Jagannathpurpatna  134    45    129    308   Medium
103                             Jayapurpatna  137    57     99    293   Medium
104                           Kalyanpursasan  136    73    138    347   Medium
105                            Kausalyaganga  153    56    103    312   Medium
106                               Khatuapada  134    67     88    289   Medium
108                                 Mohanpur  139    85    112    336   Medium

In [23]:
df[df['Category']=='High']

             Location  Men  Kids  Women  Total Category
2     Bahadalpur (og)  137   113    133    383     High
6    Kalarahanga (og)  193    51    155    399     High
9      Patrapada (og)  176    69    114    359     High
13   Sarakantara (og)  206    67    125    398     High
15           Andharua  235    37     97    369     High
27            Dasapur  201    65    105    371     High
30         Gothapatna  193    60    116    369     High
34          Jujhagada  250    94     92    436     High
39     Managobindapur  182    98    121    401     High
47       Chhotraiypur  169    75    136    380     High
49           Hatasahi  204    83    121    408     High
53       Raghunathpur  188    42    129    359     High
56    Krushnasaranpur  184    71    173    428     High
58            Singada  226    77    136    439     High
63              Dhaua  165    83    113    361     High
67           Kantunia  189    81    108    378     High
70           Nuabanta  163    75    136    374     High
77         Dashabatia  140    92    146    378     High
81             Nanput  253    50    145    448     High
84         Pandiapada  197    84     82    363     High
85            Retanga  211    55    153    419     High
90        Badadhanpur  153    44    162    359     High
92            Bikipur  272    74     67    413     High
94             Dhauli  212    90     77    379     High
98            Gelapur  257    66    117    440     High
99       Gobardhanpur  242    59    107    408     High
102           Jayapur  188    78    109    375     High

In [24]:
df.shape

(109, 6)

In [26]:
def distribute(waste):
    desc = df['Total'].describe()

    if waste < desc.loc['25%']:
        res = df[df['Category'] == 'Low']['Location'].tolist()
    elif waste < desc.loc['75%']:
        res = df[df['Category'] == 'Medium']['Location'].tolist()
    else:
        res = df[df['Category'] == 'High']['Location'].tolist()

    return str(res)

In [27]:
distribute(100)

"['Lingipur', 'Mahabhoisasan', 'Bankual(og)', 'Injana (og)', 'Kesura (og)', 'Sijuan (og)', 'Barapita', 'Bhagabatipur', 'Bhola', 'Ghangapatna', 'Haridamada', 'Krushnanagar', 'Malipada', 'Nuagan', 'Paikarapur', 'Sundarpur', 'Suanga', 'Sisupalagada', 'Barimunda', 'Gandarpur', 'Khairapada', 'Padasahi', 'Raghunathpur', 'Bijipur', 'Sijuput', 'Gangeswarpursasan', 'Krushnapur']"